/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlbumCreate: typeof import('./src/components/centerArea/Albums/AlbumCreate.vue')['default']
    AlbumTab: typeof import('./src/components/centerArea/Albums/AlbumTab.vue')['default']
    BoxItem: typeof import('./src/components/rightArea/BoxItem.vue')['default']
    ButtonUI: typeof import('./src/components/UI/ButtonUI.vue')['default']
    CreatePostForm: typeof import('./src/components/centerArea/CreatePostForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElModal: typeof import('element-plus/es')['ElModal']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InputUI: typeof import('./src/components/UI/InputUI.vue')['default']
    LogotypeComponent: typeof import('./src/components/header/LogotypeComponent.vue')['default']
    MenuItem: typeof import('./src/components/UI/MenuItem.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    PostContent: typeof import('./src/components/post/PostContent.jsx')['default']
    PostItem: typeof import('./src/components/post/PostItem.vue')['default']
    ProfileItem: typeof import('./src/components/rightArea/ProfileItem.vue')['default']
    ProfileSuggested: typeof import('./src/components/leftArea/ProfileSuggested.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/rightArea/SearchBar.vue')['default']
    SearchIcon: typeof import('./src/components/UI/SearchIcon.vue')['default']
    SuggestedProfiles: typeof import('./src/components/rightArea/SuggestedProfiles.vue')['default']
    TextEditor: typeof import('./src/components/centerArea/TextEditor.vue')['default']
    TextElement: typeof import('./src/components/UI/TextElement.vue')['default']
    TrandItem: typeof import('./src/components/rightArea/TrandItem.vue')['default']
  }
}
