/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BoxItem: typeof import('./src/components/rightArea/BoxItem.vue')['default']
    ButtonUI: typeof import('./src/components/UI/ButtonUI.vue')['default']
    CreatePostForm: typeof import('./src/components/centerArea/CreatePostForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElText: typeof import('element-plus/es')['ElText']
    InputUI: typeof import('./src/components/UI/InputUI.vue')['default']
    LogotypeComponent: typeof import('./src/components/header/LogotypeComponent.vue')['default']
    MenuItem: typeof import('./src/components/UI/MenuItem.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    ProfileItem: typeof import('./src/components/rightArea/ProfileItem.vue')['default']
    ProfileSuggested: typeof import('./src/components/leftArea/ProfileSuggested.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/rightArea/SearchBar.vue')['default']
    SearchIcon: typeof import('./src/components/UI/SearchIcon.vue')['default']
    SuggestedProfiles: typeof import('./src/components/rightArea/SuggestedProfiles.vue')['default']
    TextEditor: typeof import('./src/components/centerArea/TextEditor.vue')['default']
    TrandItem: typeof import('./src/components/rightArea/TrandItem.vue')['default']
  }
}
